### ISSUE TITLE
Admin GUI: edit ACL

### ISSUE THREAD

**Issue by boris-horner** [dewarim/cinnamon#156] opened 2017-02-20 08:55 UTC
Changing ACL parameters does not work. Steps to reproduce
* Choose an ACL from the ACL list
* Edit
* Change something (in my case, the name)
* Save

![error_acl](https://cloud.githubusercontent.com/assets/4948244/23117998/b7810d82-f752-11e6-94d4-b411561a98af.png)

**Comment by dewarim** [comment] 2018-06-30 10:12
Duplicate of #151

**Closed** 2018-06-30 10:13 UTC
Labels: duplicate
