### ISSUE TITLE
connect as a deactivated user causes 500

### ISSUE THREAD

**Issue by boris-horner** [dewarim/cinnamon#158] opened 2017-04-19 15:59 UTC
When logging on via API connect, inexistent users or wrong passwords return a clean error message. Logging on as a deactivated user causes the server to throw a 500.

**Comment by dewarim** [comment] 2017-04-19 19:41
Do you have a stacktrace? I cannot reproduce this exactly.
My desktop client just pops up a message "Failure connecting user foo to repsitory bar"

**Comment by dewarim** [comment] 2017-04-19 19:42
Never mind, found the exception in the log - but strange that it's not reported in the UI / Client.

**Comment by dewarim** [comment] 2017-04-19 20:29
Seems to be a variant of this problem:
https://github.com/grails-plugins/grails-spring-security-core/issues/412

> What is happening is that when you hit an unauthorized or missing page that is covered by the rules defined by grails.plugin.springsecurity.controllerAnnotations.staticRules = [ .. ] spring security is routing directly to the tomcat error pages rather than the correct grails pages IF your error pages are using any sort of grails layout.

The problem here is: it's a 500 error, so a generic error mapping will also capture other 500 errors.
The issue may be fixed in a newer version of Grails, but that would require us to move to Grails 3. Meh.

**Comment by boris-horner** [comment] 2017-04-20 00:03
Your client is not the latest version. When I integrated the new low-level communication layer, I also changed the analysis of the response such that errors are consequently thrown. So the new client reports some things that the version you are using simply ignores. I'll give you a copy of the client these days.

**Comment by boris-horner** [comment] 2018-04-17 10:17
Connect with inexistent user or with existing user, but wrong password returns 500. The expected behaviour would be a controlled error element with error.wrong.password or error.user.not.found. This would enable showing different messages on the client for the different types of login failures...

**Comment by dewarim** [comment] 2018-04-17 20:55
New version for testing @ https://cinnamon.dewarim.com/cinnamon.war

**Closed** 2018-06-30 09:59 UTC
